# Header

menu:
  主页: /
  相册: /photos/

# SubNav
subnav:
  qq: "tencent://message/?uin=317203829&Site=admin5.com&target=_blank"
  weixin: "/images/gerendingyuehao.jpg"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "Mailto:chenglong.990614@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: false
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: 建议打赏1-10元
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: "/images/pay/alipay.png"
# 微信二维码图片地址
weixin: "/images/pay/wxpay.png"
rss: true
# Miscellaneous
baidu_analytics: true
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: /images/avatar.jpg

#是否开启分享
jiathis: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: 'cyt71fmVn'
changyan_conf: 'prod_104709e5ada846a09f0c8c7531d635cd'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#87CEEB'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  我的CSDN: http://blog.csdn.net/gongziyayu

aboutme: '<font size="3px" color="blue">&emsp;我是一名技术不算很好的程序猿…</br>
&emsp;希望记录坑过的点点滴滴能帮助到正在焦头烂额的你们</br></br>
&emsp;我偶尔会看一些杂乱的书籍，或许阳春白雪，或许下里巴人…</br>
&emsp;希望在路过的你们能藉此消磨些许无聊</br></br>
&emsp;我偶尔会分享一些悲欢，感慨一些春秋…</br>
&emsp;希望驻足于此的你们偶尔能以吾之情浇汝之块垒</br></br>
&emsp;我还会思考一些世间情事，絮叨一些心中体悟…</br>
&emsp;希望路过的你如果看到它，能得到一丁点的帮助</br></br>
&emsp;………………</br></br>
&emsp;我是一名博主，期待与您的相遇</font>'